config/routes.rb
Rss::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }


  resources :users do
    member do
      get :following, :followers, :favorites, :timeline
    end
  end

  resources :feeds
  resources :subscriptions
  resources :articles
  resources :categories
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :timelines, only: [:create, :destroy]
  resources :activities

  get 'feeds/update/articles', to:  'feeds#update_articles', as: 'feeds_update_articles'
  post 'feeds/update/sortable', to:  'feeds#sortable', as: 'feeds_sortable'
  post 'feeds/update/middle', to:  'feeds#middle', as: 'feeds_update_middle'
  get 'feeds/update/addexternal', to:  'feeds#create_external', as: 'feeds_update_external'
  get 'feeds/update/send_xml', to:  'feeds#send_xml', as: 'feeds_send_xml'
  root to: 'users#show'
  
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  attr_accessible :description, :title, :url

  has_many :articles, dependent: :destroy
  has_many :subscriptions
  has_many :users, :through => :subscriptions

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

	def create
	end

  def send_xml
      user = User.find(params[:id])
      @articles = user.timeline_articles
      respond_to do |format|
        
        format.html {render xml: @articles}

      end
  end

  def create_external

      @feed = Feed.find_by_url(params[:url])

      feed_data = Feedjira::Feed.fetch_and_parse("#{params[:url]}")
      
      if feed_data != 0 && feed_data != 200
        @feed = Feed.new(url: params[:url])
        @feed.title = feed_data.title
        @feed.description = feed_data.description
        @feed.save
        # @subscription.feed_id = @feed.id
        # @subscription.user_id = current_user.id
        # @subscription.save
        Article.create_from_feed_data(feed_data, @feed.id)
        
      end  
      if @feed
        redirect_to :back
      else
        render json: "incorrect rss feed" 
      end
      
  end  

  def destroy
      # Feed.find(params[:id]).articles.destroy
      Feed.find(params[:id]).destroy
      redirect_to :root
  end

  def update_articles
    if (params[:id])
      @user = User.find(params[:id])
    else
      @user = current_user
    end

    feed_urls = Feed.all.map{|feed| feed.url}
    feed_urls = feed_urls.select{|f| !f.nil?}
    feed_data = Feedjira::Feed.fetch_and_parse(feed_urls)
    
    if feed_data != 0
      Article.update_from_feed_data(feed_data, feed_urls)
    end
     

    respond_to do |format|
      
      format.json {render json: feed_data}
      format.js  { render 'update_articles.js.erb'}
      format.html {redirect_to :root }
      
    end

  end

  def show
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.js  { render 'show.js.erb'}
      format.html
    end
  end

  def index

    # if params[:q].nil?
      @q = Feed.search(params[:q])
      @feeds = @q.result(:distinct => true).order("created_at desc")
    # else  
      # @feeds = Feed.all
    # end

    @subscriptions = current_user.feeds
    respond_to do |format|
      format.js  { render 'index.js.erb'}
      format.html
    end

  end

  def sortable
    @user = current_user
    @new_order = params["feed"]
    a = []
    b = []
    c = ""
    category_id = nil
    @new_order.each.with_index do |feed_id, i|
            c = @user.subscriptions.where(:feed_id => feed_id.to_i).first
          unless c.nil?   
            c.sort_order = i
            c.category_id = category_id
            c.save
            a << c
        else
            category_id = feed_id[10..-1].to_i
            b << category_id
        end
    end  

    respond_to do |format|
      format.json  { render json: [a,b]}
    end
  end

  def middle
    @partial = params["partial"]
    respond_to do |format|
      format.js  { render "categories/categorysort.js.erb"}
    end

  end

end

app/views/feeds/_feed_url.html.erb
<div class="middle-title">Manage Your Feeds</div>
Either subscribe to a feed that another user has added to
Yakety or add your own. Add catgories to help keepy your feeds organised.
<div class="middle-small-title">Add a new feed to Yakety</div>
  <%= form_tag("/subscriptions", method: "post", remote: true) do %>
   <!-- label_tag(:feed_url)  -->
  <%= text_field_tag(:feed_url) %>
  <%= submit_tag("Add") %>
  <% end %>

     <% if flash[:nofeed] %>
          <div id="NoFeedAlert"><%= flash[:nofeed] %> </div>
     <% end %>

  <div class="middle-small-title">Add a Category</div>
  <%= form_tag("/categories", method: "post", remote: true) do %>
       <!-- label_tag(:category_name) %> -->
      <%= text_field_tag :category_name,params[:category_name], id: "category_input"  %>
      <%= submit_tag("Add") %>
    <% end %>
  

app/views/feeds/_feedarticles.html.erb
<div class="middle-title"><%= @feed.title %></div>
<ul>
<% @feed.articles.most_recent.each do | article | %>

  <li>
	<%= link_to article_path(article), remote: true do %>
	    <div class="article" data-last_updated="<%= article.created_at.to_i %>">
	      <%= article.title %>
	    </div>
	<% end %>
  </li>
  <% end %>
</ul>  

app/views/feeds/_feedarticlescategory.html.erb
<div class="middle-title"><%= @category.category_name.capitalize %></div>
<ul id="showcategory" data-category="<%= @category.id %>">
  <% @articles.each do | article | %>

  <li class = "feed_<%= article.feed_id %>">
	<%= link_to article_path(article), remote: true do %>
	    <div class="article" data-last_updated="<%= article.created_at.to_i %>">
	      <%= article.title %>
	    </div>
	<% end %>
  </li>
  <% end %>
</ul>  

app/views/feeds/_feeds.html.erb
<div class="middle-small-title">Availiable Feeds</div>

  <div class="search">
    <%= search_form_for @q do |f| %>
      <%= f.text_field :title_cont, :placeholder => "Title contains" %>
      <%= f.submit %>
    <% end %> 
  </div>

  
 

<ul>
<% @feeds.each do |feed| %>
  <% unless @subscriptions.include?(feed) %>
    <li id="feeds_feed_<%= feed.id %>">
      <%= link_to feed.title, feed_path(feed), remote: true %>
      <%= feed.description %>
      <%= feed.url %>
      <%= link_to "Subscribe", subscriptions_path(:feed_url => feed.url), method: "post", remote: true %>
    </li>
  <% end %>
<% end %>
</ul>

app/views/feeds/index.html.erb
<p>example feeds</p>
<p>http://feeds.bbci.co.uk/news/rss.xml</p>
<p>http://feeds.bbci.co.uk/news/politics/rss.xml</p>
<p>http://lorem-rss.herokuapp.com/feed?unit=second&interval=30</p>

 


<%= render 'feed_url' %>

<%= render 'feeds' %>

app/views/feeds/index.js.erb
var feedHtml =  "<%= escape_javascript(render partial: '/feeds/feed_url' ) %>"
var feedHtml = feedHtml  +  "<%= escape_javascript(render partial: '/feeds/feeds' ) %>"
$('#middle-menu').html(feedHtml);

$('#middle-menu').data("partial","/feeds/feed_url");

app/views/feeds/show.html.erb
<%= render 'feedarticles' %>

app/views/feeds/show.js.erb
var articleHtml =  "<%= escape_javascript(render partial: '/feeds/feedarticles' ) %>"

$('#middle-menu').html(articleHtml)
getReady();

app/views/feeds/update_articles.js.erb
var list_of_feeds = $('.feed_title')
var last_updated = $('.feed_title').data('last_updated')

var articleHtml =  "<%= escape_javascript(render partial: '/users/articles' ) %>"

$('#articles').html(articleHtml)

$('.article').each(function(i,el){

  if($(el).data('last_updated') > last_updated){
    
    
    setTimeout(function () { 
        $(el).addClass('article_flash');
      }, 100);
    setTimeout(function () { 
        $(el).removeClass('article_flash');
      }, 1000);
    }
   
});

getReady()