config/routes.rb
Rss::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }


  resources :users do
    member do
      get :following, :followers, :favorites, :timeline
    end
  end

  resources :feeds
  resources :subscriptions
  resources :articles
  resources :categories
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :timelines, only: [:create, :destroy]
  resources :activities

  get 'feeds/update/articles', to:  'feeds#update_articles', as: 'feeds_update_articles'
  post 'feeds/update/sortable', to:  'feeds#sortable', as: 'feeds_sortable'
  post 'feeds/update/middle', to:  'feeds#middle', as: 'feeds_update_middle'
  get 'feeds/update/addexternal', to:  'feeds#create_external', as: 'feeds_update_external'
  get 'feeds/update/send_xml', to:  'feeds#send_xml', as: 'feeds_send_xml'
  root to: 'users#show'
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  include PublicActivity::Common
  
  attr_accessible :author, :category, :content, :guid, :image, :published, :summary, :title, :url, :feed_id

  belongs_to :feed

  scope :by_category, ->(category) { Article.joins(feed: {subscriptions: :category}).where(categories: {id: category.id})}
  scope :most_recent, order("published desc")


  markable_as :favorite, :timeline

  private

  def self.create_from_feed_data(feed_data, feed_id)
  	
    feed_data.entries.reverse.each do |article|
  	  create_article(article, feed_id)
  	end
  end

  def self.update_from_feed_data(feeds_data, feed_urls)

    feed_urls.each do |feed_url|
      feed_data = feeds_data[feed_url]
      feed_data.entries.reverse.each do |article|
        feed_id = Feed.where(url: feed_url).first.id
        if Article.where(guid: article.entry_id).empty?
          create_article(article, feed_id)
        end
      end

    end

  end


  def self.create_article(article, feed_id)
    
    @article = Article.create(title: article.title,
      summary: article.summary, content: article.content,
      author: article.author, published: article.published,
      url: article.url, guid: article.entry_id, feed_id: feed_id)
    begin
      @article.image = article.image
    rescue

    end
    @article.save

  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    
     @articles = Article.all

  end

	def create
		raise
	end

  def show
      @article = Article.find(params[:id])
      respond_to do |format|
    	format.js {render 'show.js.erb'}
    	format.html {render 'show.html.erb'}
   	end	

  end

  









end

app/views/articles/_addtimeline.html.erb
<%= link_to timelines_path(:id => @article.id), method: :post, remote: true do %>
	<div class='addtimeline-button'></div>
<% end %>

app/views/articles/_article.html.erb
<div class='article-header'>

<div id='published'>
  <%= @article.published %>
</div>

  <div id='fav-button'>
    <%= render 'favorite_form' %>
  </div>



  <div id='timeline-button'>
    <%= render 'timeline_form' %>
  </div>

</div> 

<div class='article-title'>
  <h1><a href=" <%=  @article.url %> " target="_blank" ><%= @article.title %></a></h1>
</div>

<div class='article-content'>
  <p><%= raw @article.summary %></p>
  <p><%= raw @article.content %></p>
  <p><%= raw @article.image %></p>

  <p class="audio_title"><%= raw @article.title %></p>

<% if @article.content && @article.content.end_with?(".mp3") %>

  <audio controls>
    <source src="<%= raw @article.content %>" type="audio/mpeg">
    <source src="<%= raw @article.content %>" type="audio/ogg">
    Your browser does not support the audio element.
  </audio>

<% end %>
  

  <video width="320" height="240" controls>
    <source src="<%= raw @article.image %>" type="video/mp4">
    <source src="<%= raw @article.image %>" type="video/ogg">
      Your browser does not support the video tag.
  </video>
  


</div>

<div class="google_plus">
  <!-- <div class="g-plus" data-action="share" data-annotation="none" data-href=" <%#=  @article.url %>" data-height="55"></div> -->

</div>
 
<a href="https://www.goolr.com/" target="_blank"id="google_share" >

  </a> 

<a href="https://www.facebook.com/sharer/sharer.php?app_id=235129946681549&sdk=joey&u=<%= @article.url %>%26ns_source%3DPublicRSS20-sa&display=popup" target="_blank"id="facebook_share" >
  </a> 


<a target=_blank href="https://twitter.com/intent/tweet?hashtags=YaketyFeed&amp;original_referer=http%3A%2F%2Flocalhost%3A3000%2Farticles%2F<%= @article.id %>&amp;text=Rss&amp;tw_p=tweetbutton&amp;url=http%3A%2F%2Flocalhost%3A3000%2Farticles<%= @article.id %>&amp;via=YaketyFeed" id="twitter_share">Tweet</a>

app/views/articles/_favorite.html.erb
<%= link_to favorites_path(:id => @article.id), method: :post, remote: true do %>
	<div class='favorite-button'></div>
<% end %>

app/views/articles/_favorite_form.html.erb
<% if current_user.favorite_articles.include?(Article.find(params[:id])) %>
	<%= render '/articles/unfavorite' %>
<% else %>
	<%= render '/articles/favorite' %>	
<% end %>

app/views/articles/_removetimeline.html.erb
<%= link_to timeline_path(:id => @article.id), method: :delete, remote: true do %>
	<div class='removetimeline-button'></div>
<% end %>

app/views/articles/_timeline_form.html.erb
<% if current_user.timeline_articles.include?(Article.find(params[:id])) %>
	<%= render '/articles/removetimeline' %>
<% else %>
	<%= render '/articles/addtimeline' %>	
<% end %>

app/views/articles/_unfavorite.html.erb
<%= link_to favorite_path(:id => @article.id), method: :delete, remote: true do %>
	<div class='unfavorite-button'></div>
<% end %>

app/views/articles/favorite.js.erb
var articleHtml =  "<%= escape_javascript(render partial: '/articles/favorite_form' ) %>"

$('#fav-button').html(articleHtml)

app/views/articles/index.html.erb
<h1> Test </h1>


<% @articles.each do |article| %>
<p><%= article.title %></p>
   <%= article.summary %>
  <%= link_to 'Show Article', article_path(article) %>

<% end %>

app/views/articles/show.html.erb
<%= render partial: 'article' %>

app/views/articles/show.js.erb
var articleHtml =  "<%= escape_javascript(render partial: '/articles/article' ) %>"

$('#right-menu').html(articleHtml)


$("#right-menu").data("partial") = "/articles/article"

app/views/articles/timeline.js.erb
var articleHtml =  "<%= escape_javascript(render partial: '/articles/timeline_form' ) %>"

$('#timeline-button').html(articleHtml)