config/routes.rb
Rss::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }


  resources :users do
    member do
      get :following, :followers, :favorites, :timeline
    end
  end

  resources :feeds
  resources :subscriptions
  resources :articles
  resources :categories
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :timelines, only: [:create, :destroy]
  resources :activities

  get 'feeds/update/articles', to:  'feeds#update_articles', as: 'feeds_update_articles'
  post 'feeds/update/sortable', to:  'feeds#sortable', as: 'feeds_sortable'
  post 'feeds/update/middle', to:  'feeds#middle', as: 'feeds_update_middle'
  get 'feeds/update/addexternal', to:  'feeds#create_external', as: 'feeds_update_external'
  get 'feeds/update/send_xml', to:  'feeds#send_xml', as: 'feeds_send_xml'
  root to: 'users#show'
  
end

app/models/user.rb
class User < ActiveRecord::Base
acts_as_marker

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable, omniauth_providers: [:twitter, :google_oauth2, :facebook]

attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :first_name, :last_name, :bio, :profile_picture_image, :profile_image

mount_uploader :profile_picture_image, ProfilePictureImageUploader



  #   def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
  #   user = User.where(:provider => auth.provider, :uid => auth.uid).first
  #   if user
  #     return user
  #   else
  #     registered_user = User.where(:email => auth.info.nickname.downcase + "@twitter.com").first
  #     if registered_user
  #       return registered_user

  #     else
        
  #       user = User.create(
  #                           provider:auth.provider,
  #                           uid:auth.uid,
  #                           email:auth.info.nickname.downcase + "@twitter.com",
  #                           profile_image: auth.info.image,
  #                           first_name: auth.info.name.split[0],
  #                         )
  #     end


  #   end
  # end


  # def self.from_omniauth(auth)
  #   if user = User.find_by_email(auth.info.email)
  #     user.provider = auth.provider
  #     user.uid = auth.uid
  #     user
  #   else
  #     where(auth.slice(:provider, :uid)).first_or_create do |user|
  #       user.provider = auth.provider
  #       user.uid = auth.uid
  #       user.email = auth.info.email
  #       user.password = Devise.friendly_token[0,20]
  #     end
  #   end
    
  # end

  # def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  #     user = User.where(:provider => auth.provider, :uid => auth.uid).first
  #     if user
  #       return user
  #     else
  #       registered_user = User.where(:email => auth.info.email).first
  #       if registered_user
  #         return registered_user
  #       else
  #         user = User.create(name:auth.extra.raw_info.name,
  #                             provider:auth.provider,
  #                             uid:auth.uid,
  #                             email:auth.info.email,
  #                             :profile_image => auth.info.image,
  #                             password:Devise.friendly_token[0,20],
  #                           )
  #       end   
  #     end
  #   end


  
  def following?(other_user)
    relationships.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by_followed_id(other_user.id).destroy
  end


  has_many :subscriptions
  has_many :feeds, :through => :subscriptions
  has_many :categories
  has_many :articles, :through => :feeds

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower


  $bookmarklet = "
      javascript: (
      function () { 
            var myElements = document.getElementsByTagName('a');
      var node=document.createElement('ul');
      var title = document.createElement('h2');
      var title_text = document.createTextNode('Rss feeds on this page - add to Yakety!');
      title.appendChild(title_text);
      node.appendChild(title);
      var close = document.createElement('a');
      var closetest = document.createTextNode('CLick to close');
      close.appendChild(closetest);
      close.href = 'javascript:history.go(0)';
      close.setAttribute('style','color: white; width: 200px; display: inline-block; float:right');        
      node.appendChild(close);
      
      for (var i = 0; i < myElements.length; i++) {
        if (myElements[i].href.indexOf('.xml') > -1) {
            var list = document.createElement('li');

            var listitem =  document.createElement('span');
            var listitem_text = document.createTextNode(myElements[i].text + ': ' );
            listitem.appendChild(listitem_text);
            listitem.setAttribute('style','color: white; width: 200px; display: inline-block; overflow:hidden');        
            list.appendChild(listitem);

            var itemurl = document.createElement('a');
            var itemurl_text = document.createTextNode(myElements[i].href);
            itemurl.appendChild(itemurl_text);
            itemurl.href= myElements[i].href;
            itemurl.setAttribute('style','color: white; margin-left: 50px; width: 200px; display: inline-block; overflow:hidden');        
            list.appendChild(itemurl);
            
            var postit = document.createElement('a');
            var postit_text = document.createTextNode('Add to Yakety');
            postit.appendChild(postit_text);
            postit.href = 'http://yakety.herokuapp.com/feeds/update/addexternal?url=' + myElements[i].href;
            postit.setAttribute('style','color: white; margin-right: 100px; font-weight: bold; display: inline-block; margin-left: 100px');
            list.appendChild(postit);  
          
            node.appendChild(list);
          };
        }; 
        
        node.setAttribute('style','position: fixed; top: 10px; background-color: #ca2024; z-index: 100000000000000; color: white; list-style: none; height: 500px; overflow: scroll; border: 10px solid white; left: 15%; padding: 10px');
        document.getElementsByTagName('body')[0].appendChild(node);
      }());"
  

  def self.from_omniauth(auth)
    twitter_email = if auth.info.nickname then auth.info.nickname.downcase + "@twitter.com" end
     
    if user = User.find_by_email(auth.info.email) || user = User.find_by_email(twitter_email) 
      user.provider = auth.provider
      user.uid = auth.uid
      # user.profile_image = auth.info.image
      user
    else
      if auth.provider == "twitter"
        user = User.create({
              :provider => auth.provider,
              :uid => auth.uid,
              :email => auth.info.nickname.downcase + "@twitter.com",
              :first_name =>  auth.info.name.split(" ")[0],
              :last_name =>  auth.info.name.split(" ")[1],
              :bio => auth.info.description,
              :profile_image => auth.info.image,
              :password => Devise.friendly_token[0,20]
          })
          
      else
        
        where(auth.slice(:provider, :uid)).first_or_create do |user|
            user.provider = auth.provider
            user.uid = auth.uid
            user.email = auth.info.email
            user.first_name = auth.info.first_name
            user.last_name = auth.info.last_name
            user.profile_image = auth.info.image
            user.password = Devise.friendly_token[0,20]
        end
      end 
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_filter :authenticate_user!

	def index
    @user = current_user
 		@users = User.all

    respond_to do |format|
        format.js  { render '/users/index.js.erb'}
        format.html { render '/users/index.js.erb'}
      end
	end

	def show
    if (params[:id])
      @user = User.find(params[:id])
    else
		  @user = current_user
    end
      @following = @user.followed_users

      @activities = PublicActivity::Activity.order("created_at desc").where(owner_id: current_user.followed_users, owner_type: "User")

      @q = Feed.search(params[:q])
      @feeds = @q.result(:distinct => true)
      @subscriptions = current_user.feeds

      b = []
      @activities.each do |activity|
          if activity.created_at.to_i > params[:since].to_i
              a = {}
              a["first_name"] = activity.owner.first_name 
              a["last_name"] = activity.owner.last_name
              a["id"] = activity.trackable.id 
              a["title"] = activity.trackable.title
              a["created"] = activity.created_at.to_i
              a["since"] = params[:since].to_i
              b << a 
          end
      end 
      
      respond_to do |format| 
        format.json {render json: b.reverse}

        format.html
      end
	end

  def edit
    @user = User.find(params[:id])
    respond_to do |format|
        format.html {render '/users/edit.html.erb'}
        format.js {render '/users/edit.js.erb'}
    end
  end

  def update
    @user = User.find(params[:id])
    # raise
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

	def following
	    @title = "Following"
	    @user = User.find(params[:id])
	    @users = @user.followed_users
	    render 'show_follow'
  	end

 	def followers
	    @title = "Followers"
	    @user = User.find(params[:id])
	    @users = @user.followers
	    render 'show_follow'
  	end

  	def favorites
  		user = current_user
  		@articles = user.favorite_articles
  		render 'favorites'
  	end

  	def timeline
  		@user = User.find(params[:id])
  		@articles = @user.timeline_articles
  		render 'timeline'
  	end

end

app/views/users/_activities.html.erb
<% if @activities.length > 0 %>
  <div class='middle-title' id='activity-stream' data-since="<%= @activities.first.created_at.to_i %>" data-user="<%= current_user.id %>">Recent Activity</div>
<% end %>

<% @activities.each do |activity| %>
<div class='wide-display'>
	  <b><%= activity.owner.first_name %> <%= activity.owner.last_name %></b> has <b>added</b> an article to their <b>timeline</b>
	  
	  	<%= link_to article_path(activity.trackable), remote: true do %>
	  		<%= activity.trackable.title %>
	  	<% end %>
</div>
<% end %>

app/views/users/_allusers.html.erb
<div class='middle-title' id='user-search'>Connect with other Yakety users</div>

	<% @users.each do |user| %>
		<div class='user-search'>
				<% unless user.id == current_user.id %>	

					<div class="userimage_all">
						<% if user.profile_picture_image.file %>
      				<%= image_tag user.profile_picture_image %>
    				<% elsif user.profile_image %>
      				<%= image_tag user.profile_image %>
    				<% else %>
      				<img src="/assets/mega-phone-white.png" >
    				<% end %> 
    			</div>


				<% if user.first_name.nil? || user.first_name == "" %>
					<p> <%= user.email %> </p>
				<% else %>
					<p><%= user.first_name %> <%= user.last_name %></p>
				<% end %>

			<div id="followpicture">
				<% if current_user.following?(user) %>
					<%= link_to relationship_path(:id => user.id), method: :delete, remote: true do %>	
						<div class='unfollow-button'></div>
					<% end %>
				<% else %>	
					<%= link_to relationships_path(:id => user.id), :action => 'create', method: :post, remote: true do %>
						<div class='follow-button'></div>
					<% end %>
				<% end %>
			</div>
			<% end %>


		</div>
	<% end %>
	

app/views/users/_articles.html.erb
<h2>Articles</h2>
<% @user.feeds.each do | feed | %>
  <h2 class="feed_title" data-last_updated="<%= feed.articles.most_recent.first.created_at.to_i %>" data-feed_id="<%= feed.id %>"><%= feed.title %></h2>
  <% feed.articles.most_recent.each do | article | %>

	<%= link_to article_path(article), remote: true do %>
	    <div class="article" data-last_updated="<%= article.created_at.to_i %>">
	      <h3><%= article.title %></h3>
	      <p><%= article.summary %></p>
	      <!-- <a href="<%= article.url %>">Read More...</a> -->
	    </div>
	<% end %>
  <% end %>
<% end %>

app/views/users/_feed_url.html.erb
<%= form_tag("/subscriptions", method: "post") do %>
  <%= label_tag(:feed_url, "URL:") %>
  <%= text_field_tag(:feed_url) %>
  <%= submit_tag("Add") %>
<% end %>

  

app/views/users/_feeds_menu.html.erb
  <% @user.feeds.includes(:subscriptions).where("subscriptions.category_id is Null").order("subscriptions.sort_order").each do | feed | %>

        <li id="feed_<%= feed.id %>"><%= link_to feed.title, feed_path(feed), remote: true %>                 
            <%= link_to subscription_path(find_subscription(feed,current_user)), method: :delete, class: "delete_icon", remote: true do %>
                <img src="/assets/delete.png" >
            <% end %>
        </li> 
      <% end %>

      <% @user.categories.each do |category| %>
        <% i = 1 %>
        <li class="menu-small-title categoryheader" id="feed_[category]<%= category.id %>" data-category="<%= category.id %>"> 
          <%= link_to category.category_name.capitalize, category_path(category), remote: true %>
            <%= link_to category_path(category), method: :delete, class: "delete_icon", remote: :true do %>
                <img src="/assets/delete.png" >
              <% end %>

          </li>
          <% @user.feeds.where("subscriptions.category_id = #{category.id}").order("subscriptions.sort_order").each do |feed|%>
              <li id="feed_<%= feed.id %>" class="category<%= category.id %>" data-category="<%= category.id %>"><%= link_to feed.title, feed_path(feed), remote: true, data: { color: i, feedId: feed.id } %>  
              <%= link_to subscription_path(find_subscription(feed,current_user)), method: :delete, class: "delete_icon", remote: :true do %>
                <img src="/assets/delete.png" >
              <% end %>
          </li> 
          <% end %>
        
        <% end %>
      

app/views/users/_follow_form.html.erb
<% unless current_user.id == user.id %>
	<% if current_user.following?(user) %>
		<%= render 'unfollow' %>
	<% else %>
		<%= render 'follow' %>
	<% end %>
<% end %>

app/views/users/_userprofile.html.erb
<div class='middle-title' id='profile'>
  
<% if @user.first_name == "" || @user.first_name.nil? %>
  
  User

<% else %>
    <%= @user.first_name %> <%= @user.last_name %>
  <% end %>
</div>
<% if @user.profile_picture_image.file %>
    <div class='profile-picture'><%= image_tag @user.profile_picture_image %></div>
<% elsif @user.profile_image %>
    <div class='profile-picture'><%= image_tag @user.profile_image %></div>
  <% else %>
      <div class='profile-picture'> <img src="/assets/mega-phone-white.png" ></div>
  <% end %> 

  <div class='bio'><%= @user.bio %></div>


  <div class='stats'><%= render '/shared/stats' %></div>

  <%= render '/shared/followed' %>
  <%= render '/shared/followers' %>

  <h2>Your Categories</h2>
  <% @user.categories.each do |category| %>

  	<% if category.cover_image %>	
  			<%= link_to category_path(category), remote: true do %>
            <img class='category-box' src="<%= category.cover_image %>" >
        <%= category.category_name.capitalize %>
  			<% end %>
  	<% else %>	
  			<%= link_to category_path(category), remote: true do %>
  			<div class='category-box category-box-background'></div><%= category.category_name.capitalize %>
  			<% end %>
  		<% end %>

  <% end %>
</div>

app/views/users/_users.html.erb
<ul>
  <div class="menu-title">Following
      <div class='follower-search-button'></div>
  		<%= link_to users_path, remote: true do %>
  		    <div class='follower-add-button'></div>
  		<% end %>
  	</div>
</ul>

<div id='following-list-search'>
	<input type='text' id='filter' placeholder='Search Followers'>
</div>

<ul id='following'>
	<% @following.each do |user| %>
    <% if user.first_name.nil? %>
    <li><%= link_to "#{user.email}", timeline_user_path(user), remote: true %></li>
    <% else %>
	 	<li><%= link_to "#{user.first_name} #{user.last_name}", timeline_user_path(user), remote: true %></li>
    <% end %>
	<% end %>
</ul>

app/views/users/_usertimeline.html.erb
<% if @user.nil? %>
	<a href="../feeds/update/send_xml/?id=<%= current_user.id %>" target="_blank"><div class="middle-title">Timeline</div></a>
<% else %>
	<a href="../feeds/update/send_xml/?id=<%= @user.id %>" target="_blank"><div class="middle-title">Timeline</div></a>
<% end %>


<% @articles.each do |article| %>
	<div class='wide-display'>
		<%= link_to article_path(article), remote: true do %>
		      <%= article.title %>
		<% end %>
		<div id='feed-source'>
		<%= link_to feed_path(article.feed_id), remote: true do %>
		      <%= article.feed.title %>
		<% end %>
		</div>
	</div>
<% end %>

app/views/users/index.html.erb
<%= render '/users/allusers' %>

app/views/users/index.js.erb
var articleHtml =  "<%= escape_javascript(render partial: '/users/allusers' ) %>"

$('#middle-menu').html(articleHtml)

app/views/users/show_follow.html.erb
<h1><%= @user.first_name %>'s Relationships</h1>
<%= link_to "Back to Profile", @user %>

<%= render 'shared/stats' %>

<h2><%= @title %></h2>

<%= render 'users' %>

app/views/users/timeline.html.erb
<%= render 'usertimeline' %>

app/views/users/timeline.js.erb
var articleHtml =  "<%= escape_javascript(render partial: '/users/usertimeline' ) %>"

$('#middle-menu').html(articleHtml)