config/routes.rb
Rss::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }


  resources :users do
    member do
      get :following, :followers, :favorites, :timeline
    end
  end

  resources :feeds
  resources :subscriptions
  resources :articles
  resources :categories
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :timelines, only: [:create, :destroy]
  resources :activities

  get 'feeds/update/articles', to:  'feeds#update_articles', as: 'feeds_update_articles'
  post 'feeds/update/sortable', to:  'feeds#sortable', as: 'feeds_sortable'
  post 'feeds/update/middle', to:  'feeds#middle', as: 'feeds_update_middle'
  get 'feeds/update/addexternal', to:  'feeds#create_external', as: 'feeds_update_external'
  get 'feeds/update/send_xml', to:  'feeds#send_xml', as: 'feeds_send_xml'
  root to: 'users#show'
  
end

app/views/layouts/_signin.html.erb
<div class="signinbutton">
  <a class="buttonSignUp" href="#popup1">Sign Up</a> 
  <a class="buttonSignIn" href="#popup2">Sign In</a>
</div>       

<div id="popup1" class="overlay">
  <div class="popup">
    <h2>Sign Up</h2>
    <a class="close" href="#">&times;</a>
    <div class="content">
    </div>
    <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>
      <div>
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>
      <div>
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>
      <div>
        <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation,  autocomplete: "off" %>
      </div>
      <div>
        <%= f.submit "Sign up" %>
      </div>
    <% end %>
  </div>
</div>

<div id="popup2" class="overlay light">
  <a class="cancel" href="#"></a>
  <div class="popup">
    <hr style="width:0.5px; height:330px; position: absolute; left: 250px;"/>
    <h2>Sign in</h2>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div>
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: true %>
        </div>
        <div>
          <%= f.label :password %><br />
          <%= f.password_field :password, autocomplete: "off" %>
        </div>
        <% if devise_mapping.rememberable? %>
          <div>
            <%= f.check_box :remember_me %> 
            <%= f.label :remember_me %>
          </div>
        <% end %>
        <div>
          <%= f.submit "Sign in" %>
        </div>
    <% end %>

    <%= link_to user_omniauth_authorize_path(:twitter) do %>
        <div id="twitter-logo"></div>
    <% end %>
      
    <%= link_to user_omniauth_authorize_path(:google_oauth2) do %>
        <div id="google-logo"> </div>
    <% end %>             
      
    <%= link_to user_omniauth_authorize_path(:facebook) do %>
        <div id="facebook-logo"> </div>
    <% end %>

    <hr style="width:0.5px; height:330px; position: absolute; left: 550px; margin-top:-160px;"/>
      
    <div class="new_user_login">
      <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= devise_error_messages! %>

            <h2 id="sign-up">Sign Up</h2>
          <div>
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true %>
          </div>
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "off" %>
          <div>
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: "off" %>
          </div>
              <%= f.submit "Sign up" %>
            
      <% end %>
    </div>

</div>
</div> 

app/views/layouts/_socialmedia.html.erb
<div id="socialboxbtn-container">
  <a href="https://www.facebook.com/profile.php?id=100008346759587" class="socialboxbtn socialboxfb" target="_blank">Like on Facebook</a>
  <a href="https://twitter.com/YaketyFeed" class="socialboxbtn socialboxtw" target="_blank">Follow on Twitter</a>
  <a href="https://plus.google.com/u/0/105022915175785201051/posts" class="socialboxbtn socialboxgp" target="_blank">Plus on Google+</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yakety Feeds</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Arimo:400,700' rel='stylesheet' type='text/css'>

  <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
 
  
</head>
<body>
 

<header>

  <div class="login">
   

    <% if @user.profile_picture_image.file %>
        <%= image_tag @user.profile_picture_image %>
    <% elsif @user.profile_image %>
      <%= image_tag @user.profile_image %>
    <% else %>
      <img src="/assets/mega-phone-white.png" >
    <% end %> 

    <% if user_signed_in? %>
      Hello <%= current_user.first_name %>. 

      <%= link_to "Sign out", destroy_user_session_path,:method => :delete %>
       

    <% else %>
      <%= render partial: 'layouts/signin' %>
    <% end %>
  </div>

  <div class="login" id="login-right">
      
      <!-- link_to "update articles ajax", feeds_update_articles_path, remote: true  -->
      <a id="bookmarklet" href="<%= $bookmarklet %>">Find Feeds</a>

      <%= link_to edit_user_path(current_user), remote: true do %>
      <div class="settings"> </div>
      <% end %>



  </div>
    
   <%= link_to  root_path do %> 
   <div class="small_logo"> </div>
   <% end %>

  

  <p class="alert"><%= alert %></p>

</header>

  <%= yield %>

  <div class="social-media">
  <%= render partial: 'layouts/socialmedia' %>
  </div>  

</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rss</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>


    <% if user_signed_in? %>
      <%= link_to "Add a feed", users_path %>
      <%= link_to "user page", user_path(current_user) %>
    <% end %> 

  <p class="alert"><%= alert %></p>
  <div class="sign-in-buttons">
    <%= render partial: 'layouts/signin' %>
  </div>

  <%= yield %>



    

</body>
</html>